# To test if your modification to this file works, go to http://lint.travis-ci.org/.
language: c
env:
  CXX=g++-4.8
  ANDROID_HOME=$PWD/android-sdk-linux
  PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2
os:
  - linux
  - osx
cache:
  directories:
    - haoshiyou/node_modules
notifications:
  slack: haoshiyou:eSZq9zT9wMllEJYHMITggGky
before_install:
  - $HOME/.nvm/nvm.sh
  - nvm install v4
  - cd haoshiyou 
  # download config.json from haoshiyou-security repository with a token
  - ./travis/download-config.sh
  - ./travis/install-platform-sdk.sh
install:
  - ./travis/install-ionic-sdk.sh
  - npm install
script:
  - ./travis/build-platform.sh
