# To test if your modification to this file works, go to http://lint.travis-ci.org/.
language: node_js
env:
  CXX=g++-4.8
node_js:
  - '6.9'
matrix:
  fast_finish: true
os:
  - linux
  - osx
notifications:
  slack: haoshiyou:eSZq9zT9wMllEJYHMITggGky
before_install:
  - cd haoshiyou
  # download config.json from haoshiyou-security repository with a token
  - ./travis/download-config.sh
install:
  - ./travis/install-platform-sdk.sh
  - ./travis/install-ionic-sdk.sh
  - npm install
script:
  - ./travis/build-platform.sh
